config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :user do
    resources :desks, only: [:index]
    # get 'openhouse', to: "desks#openhouse", as: "openhouse"
    resources :clients, except: [:show,:index] do
      resources :events, except: [:show,:index]
    end    
  end

  devise_for :users, controllers: { sessions: "users/sessions", confirmations: 'users/confirmations',
                                    :registrations => 'users/registrations', :passwords => 'users/passwords',
                                    :mailer => 'users/mailer' }

  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
    get "sign_up", to: "users/registrations#new"
    get "forgot_password", to: "users/passwords#new"
  end

  get 'edit_password', to: "user#edit", as: 'edit_password'
  patch 'update_password', to: "user#update_password", as: 'update_password'
  
  
  get 'edit_profile', to: "user#edit_profile", as: "edit_profile"
  patch 'update_profile', to: "user#update_profile", as: 'update_profile'

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/user/clients_controller.rb
class User::ClientsController < ApplicationController

  def new
    @client = Client.new
    @client_info = true
  end

  def create
    @client = Client.new(client_params)
    if @client.save && params[:proceed_next]
      redirect_to new_user_client_event_path(@client.id), notice: "Client saved"
    else
      render action: "new"
    end
  end

  def edit
    @client = Client.find(params[:id])
    @client_info = true
  end

  def update
    @client_info = true
    @client = Client.find(params[:id])
    if @client.update_attributes(client_params)
      redirect_to new_user_client_event_path(@client.id), notice: "Client Updated"
    else
      render 'edit'
    end
  end

private
  def client_params
    params.require(:client).permit(:chain, :business_unit, :address, :postal_code, :first_name, :last_name, :title, :phone_number, :email, :city, roles:[])
  end
end

app/controllers/user/desks_controller.rb
class User::DesksController < ApplicationController

  def index
    @start = true
  end

end

app/controllers/user/events_controller.rb
class User::EventsController < ApplicationController
  def new
    @event_info = true
    @event = Event.new
    @client = Client.find(params[:client_id])
  end

  def edit
    @event = Event.find(params[:id])
    @event_info = true
  end

  def update
    @event_info = true
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      redirect_to root_path, notice: "Event Updated"
    else
      render 'edit'
    end
  end  

  def create
    @event_info = true
    @event = Event.create(event_params)
    if @event.save
      redirect_to root_path, notice: "Event saved"
    else
      render action: "new"
    end
  end

  private
  def event_params
    params.require(:event).permit(:client_id , :planning_date, :event_date, :start_time, :end_time, :no_of_rooms, :time_per_customer, :price, :tmms)
  end  
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_filter :authenticate_user!, :except => [:show]

  def edit
  end

  def update_password
    user = current_user
    if current_user.update_attributes(user_params)
      sign_in user, :bypass => true
      flash[:notice] = I18n.t("general.password_updated_successfully")
      redirect_to edit_password_path
    else
      render "edit"
    end
  end

  def edit_profile    
  end
  
  def update_profile
    if current_user.update_attributes(edit_user_params)
      flash[:notice] = I18n.t("general.profile_updated_successfully")
      redirect_to edit_profile_path
    else
      render "edit_profile"
    end
  end

  def show
    @user = User.find params[:id]
    prepare_meta_tags title: @user.full_name, description: @user.role, keywords: @user.full_name
  end

  private

  def user_params
    # NOTE: Using `strong_parameters` gem
    params.require(:user).permit(:password, :password_confirmation)
  end

  def edit_user_params
    params.require(:user).permit(:first_name, :last_name, :avatar)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end

  private 

  def after_sign_in_path_for(resource)
    # user_gases_path
    root_path
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user/desk_helper.rb
module User::DeskHelper
end

app/views/user/edit.html.haml
= form_for(current_user, url: update_password_path, :html => {:class => "form-horizontal"}) do |f|
  = f.hidden_field :reset_password_token
  %fieldset
    %legend
      = t('general.change_password')
    .form-group
      %label.col-lg-2.control-label
      .col-lg-10
        - if alert.present?
          .alert.alert-dismissible.alert-danger
            %button.close{"data-dismiss" => "alert", :type => "button"} ×
            %a.alert-link{:href => "#"}
              = alert

    .form-group{:class => (current_user.errors["password"].any? ? "has-error" : '')}
      %label.col-lg-2.control-label{:for => "inputPassword"} 
        = t('change_password.new_password')
      .col-lg-10
        = f.password_field :password, autofocus: true, autocomplete: "off", placeholder: t('change_password.new_password'), :class => "form-control"
        - if current_user.errors["password"].any?
          .errorMsg
            = current_user.errors["password"].first

    .form-group{:class => (current_user.errors["password_confirmation"].any? ? "has-error" : '')}
      %label.col-lg-2.control-label{:for => "inputPassword"} 
        = t('change_password.confirm_password')
      .col-lg-10
        = f.password_field :password_confirmation, autocomplete: "off", placeholder: t('change_password.confirm_password'), :class => "form-control"
        - if current_user.errors["password_confirmation"].any?
          .errorMsg
            = current_user.errors["password_confirmation"][0]        
    .form-group
      .col-lg-10.col-lg-offset-2        
        = f.submit t('change_password.change_my_password'), :class => "btn btn-success"

app/views/user/edit_profile.html.haml
= form_for(current_user, url: update_profile_path, :multipart => true, :html => {:class => "form-horizontal"}) do |f|
  %fieldset
    %legend
      = t('general.edit_profile')
    .form-group
      %label.col-lg-2.control-label
      .col-lg-10
        - if alert.present?
          .alert.alert-dismissible.alert-danger
            %button.close{"data-dismiss" => "alert", :type => "button"} ×
            %a.alert-link{:href => "#"}
              = alert
    .form-group{:class => (current_user.errors["first_name"].any? ? "has-error" : '')}
      %label.col-lg-2.control-label{:for => "inputFirstName"} First Name
      .col-lg-10
        = f.text_field :first_name, autofocus: true, placeholder: t('signup.fname'), :class => "form-control"
        - if current_user.errors["first_name"].any?
          .errorMsg
            = current_user.errors["first_name"][0]        
    .form-group{:class => (current_user.errors["last_name"].any? ? "has-error" : '')}
      %label.col-lg-2.control-label{:for => "inputLastName"} Last Name
      .col-lg-10
        = f.text_field :last_name, autofocus: true, placeholder: t('signup.lname'), :class => "form-control"
        - if current_user.errors["last_name"].any?
          .errorMsg
            = current_user.errors["last_name"][0]

    .form-group
      %label.col-lg-2.control-label
      .col-lg-10
        = f.file_field :avatar
        - if current_user.errors["avatar"].any?
          .errorMsg
            = current_user.errors["avatar"][0]

    - if f.object.avatar.present?
      .form-group
        %label.col-lg-2.control-label
        .col-lg-10
          = image_tag f.object.avatar(:thumb)

    .form-group
      .col-lg-10.col-lg-offset-2        
        = f.submit t('general.update') , :class => "btn btn-success"

app/views/user/show.html.haml
.row
  .col-lg-12.mb20
    .left
      - prev = @user.prev
      - if prev.present? 
        = link_to image_tag("pre-arrow.png"), user_path(prev)
    .right
      - nxt = @user.next
      - if nxt.present? 
        = link_to image_tag("next-arrow.png"), user_path(nxt)
.jumbotron
  .listingDiv
    .row    
      .col-lg-12
        .left
          %p.text-info
            = @user.full_name
    .row
      .col-lg-12
        %table.table.table-striped.table-hover
          %tr
            %td
              %h4= link_to t("user.number_of_stacks", count: @user.stacks.count), stacks_path(:user => @user.id)
          %tr
            %td
              %h4= link_to t("user.number_of_products", count: @user.products.count), root_path(:user => @user.id)